/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Operations } from "./Operations";
export * as factories from "./factories";
export { Operations__factory } from "./factories/Operations__factory";
