export const linksMapByName = {
  newOperations: "new-operations",
  operations: "operations",
  incomingOperations: "incoming-operations",
  ongoingOperations: "ongoing-operations",
  engagementNotary: "engagement-notary",
  deposit: "deposit",
  minute: "minute",
  initializeTaxPayment: "initialize-tax-payment",
  taxPayment: "tax-payment",
  formalizeGuaranties: "formalize-guaranties",
  beneficiaryPayment: "beneficiary-payment",
  acceptTaxPayment: "accept-tax-payment",
  fundsDeposit: "funds-deposit",
  ended: "ended",
  initiateBeneficiary: "initiate-beneficiary",
} as const;
